### PR TITLE
fix: Search form submit on touch devices

### LINKED ISSUE #2225: Search form cannot be submitted from input text field
**Describe the bug**
Search form cannot be submitted from input text field

**To Reproduce**

1. Use a touch device
2. Go to https://orcid.org/
3. Tap on the "Search..."
4. Tap on the keyboard "return" key -> it does not have any effect.
5. Tap on the search icon button -> this is the only way to submit the form and search.

**Expected behavior**
Tapping on the "return" key when focused on the text field should submit the form and trigger the search. This is the default behaviour of forms on the web.

**Screenshots**
screenshot showing input field with some text and the iOS keyboard

**Smartphone:**

- Device: iPhone 11
- OS: 17.4.1
- Browser: Safari
- Version: 17.4

### PR DESCRIPTION
**Pull request by ptamarit**
Fixes #2225

I followed the [example of a basic Angular form from the official Angular tutorial](https://angular.io/tutorial/first-app/first-app-lesson-12#step-3---add-the-forms-markup-to-the-details-page) in order to fix the form behavior.

The changes are:
- Added `submit` event handler to the `form`.
- Removed the `keyup.enter` event handler from the `div` surrounding the `input`, since the default behavior of an `input` field is to submit the parent `form` on enter/return.
- Changed the `type` of the `button` from `button` to `submit`, so that it submits the parent `form`.
- Removed the `click` handler from the `button`, since submitting the parent `form` is enough.

Remarks:
- One potential improvement would be to change the `input` field `type` to `search`, so that the iOS keyboard would show a "search" key instead of the default "return". However, this might also change the styling of the input text.
- Another potential improvement would be to loose the focus on the input text field when submitting in order to automatically hide the keyboard. Focusing on the first search result could potentially improve accessibility (although I'm not an accessibility expert).

### CODE REVIEW

**Comment by amontenegro** [comment]
@leomendoza123 could you please review this? Thanks

**Review by leomendoza123 — APPROVED** [review]

**Comment by leomendoza123** [comment]
[[Tech] Review external contributions](https://trello.com/c/VGeIddI8/1172-tech-review-external-contributions)

**Comment by leomendoza123** [comment]
The following card has been created to QA this change. https://trello.com/c/VGeIddI8/1172-tech-review-external-contribution. 

@ptamarit thank you for your PR and improvement suggestions.

**Comment by ptamarit** [comment]
Amazing, I confirm that I can now trigger a search with the "return" key on iOS.
Thanks a lot for considering and integrating my pull request!

**Pull request merged**
