### PR TITLE
Fix/9084-qa-record-header-spacing-layout-records-with-special-status

### PR DESCRIPTION
**Pull request by DanielPalafox**

### CODE REVIEW

**Comment by DanielPalafox** [comment]
[[QA] Record header - Spacing & layout (Mobile)](https://trello.com/c/UCdDRPyM/9083-qa-record-header-spacing-layout-mobile)

**Comment by DanielPalafox** [comment]
[[QA] Record header spacing & layout - Records with special status](https://trello.com/c/jb1q8Dow/9084-qa-record-header-spacing-layout-records-with-special-status)

**Comment by DanielPalafox** [comment]
[[QA] Record header spacing & layout (Desktop)](https://trello.com/c/yDeOMFSQ/9085-qa-record-header-spacing-layout-desktop)

**Comment by DanielPalafox** [comment]
[[QA] Record header for deprecated record missing link to the record that was kept](https://trello.com/c/2NK6wTtP/9089-qa-record-header-for-deprecated-record-missing-link-to-the-record-that-was-kept)

**Review by amontenegro — APPROVED** [review]

**Pull request merged**
