### PR TITLE
Add OBO support to the sidebar

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
[[QA] Sidebar not display OBO data on the public page](https://trello.com/c/pYY0pHZ0/7549-qa-sidebar-not-display-obo-data-on-the-public-page)

**Comment by leomendoza123** [comment]
[[QA] Equal names are not grouped on the new public page [1]](https://trello.com/c/IYcdQBV6/7548-qa-equal-names-are-not-grouped-on-the-new-public-page-1)

**Comment by leomendoza123** [comment]
[[QA][my-orcid] User OBO source not displayed correctly in sidebar modals](https://trello.com/c/ZlLePfsD/7554-qamy-orcid-user-obo-source-not-displayed-correctly-in-sidebar-modals)

**Comment by leomendoza123** [comment]
[[QA][my-orcid] Created date of names not displayed correctly](https://trello.com/c/8QoSk16h/7557-qamy-orcid-created-date-of-names-not-displayed-correctly)

**Review by DanielPalafox — APPROVED** [review]

**Comment by leomendoza123** [comment]
[[QA][my-orcid] Whitespace in bio modals not trimmed](https://trello.com/c/UT0OzJ0v/7561-qamy-orcid-whitespace-in-bio-modals-not-trimmed)

**Pull request merged**
