### PR TITLE
Leo/batch of fixes bibtext

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
[[QA] Curly brackets around contributors names in works added from BibTeX](https://trello.com/c/WjAaCOAj/8344-qa-curly-brackets-around-contributors-names-in-works-added-from-bibtex)

**Comment by leomendoza123** [comment]
[[QA] Contributor display issue for citations that end author list with "and"](https://trello.com/c/09ycENXh/8347-qa-contributor-display-issue-for-citations-that-end-author-list-with-and)

**Comment by leomendoza123** [comment]
[[QA] Contributor display issue for citations that end author list with "and"](https://trello.com/c/09ycENXh/8347-qa-contributor-display-issue-for-citations-that-end-author-list-with-and)

**Comment by leomendoza123** [comment]
[Remove the record holder as default contributor for BibTeX imports](https://trello.com/c/VIMtVoJj/8365-remove-the-record-holder-as-default-contributor-for-bibtex-imports)

**Review by amontenegro — APPROVED** [review]

**Pull request merged**
