### PR TITLE
Fix hint and adding missing property

### PR DESCRIPTION
**Pull request by DanielPalafox**
https://trello.com/c/QOwC3jOQ/6730-qa-signin-xx-language-not-available-for-all-strings

### CODE REVIEW

**Comment by DanielPalafox** [comment]
[[QA] Signin: XX language not available for all strings](https://trello.com/c/QOwC3jOQ/6730-qa-signin-xx-language-not-available-for-all-strings)

**Comment by DanielPalafox** [comment]
[[QA] Signin: XX language not available for all strings](https://trello.com/c/QOwC3jOQ/6730-qa-signin-xx-language-not-available-for-all-strings)

**Comment by amontenegro** [comment]
@DanielPalafox please fix the merge monster!

Thanks

**Comment by DanielPalafox** [comment]
@amontenegro Done!

**Pull request merged**
