### PR TITLE
Fix/9086-qa-add-placeholder-copy-in-sidebar-when-no-personal-info-is-available

### PR DESCRIPTION
**Pull request by DanielPalafox**

### CODE REVIEW

**Comment by DanielPalafox** [comment]
[[QA] Record header - Spacing & layout (Mobile)](https://trello.com/c/UCdDRPyM/9083-qa-record-header-spacing-layout-mobile)

**Comment by DanielPalafox** [comment]
[[QA] Remove unwanted whitespace from locked record public page](https://trello.com/c/dFMXCNGi/9090-qa-remove-unwanted-whitespace-from-locked-record-public-page)

**Comment by DanielPalafox** [comment]
[[QA] Fix typo in string displayed when there's no public info available](https://trello.com/c/Bm1avmFg/9087-qa-fix-typo-in-string-displayed-when-theres-no-public-info-available)

**Comment by DanielPalafox** [comment]
[[QA] Add placeholder copy in sidebar when no personal info is available](https://trello.com/c/qWLqykb6/9086-qa-add-placeholder-copy-in-sidebar-when-no-personal-info-is-available)

**Comment by DanielPalafox** [comment]
[[PROD] Personal information panel not long enough to display countries when there are no activities](https://trello.com/c/86057mZE/9082-prod-personal-information-panel-not-long-enough-to-display-countries-when-there-are-no-activities)

**Review by amontenegro — APPROVED** [review]

**Pull request merged**
