### PR TITLE
batch-fixes

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
[[QA] Email domains interstitial shown to users that have already seen it](https://trello.com/c/kGSsA9Mv/9520-qa-email-domains-interstitial-shown-to-users-that-have-already-seen-it)

**Comment by leomendoza123** [comment]
[[QA] Fix display of locked account notice panel together with email domains confirmation panel](https://trello.com/c/U3MhEqnv/9519-qa-fix-display-of-locked-account-notice-panel-together-with-email-domains-confirmation-panel)

**Comment by leomendoza123** [comment]
[[QA] Accessibility issue with email domains interstitial confirmation panel displayed in my-orcid](https://trello.com/c/18vKzlSr/9518-qa-accessibility-issue-with-email-domains-interstitial-confirmation-panel-displayed-in-my-orcid)

**Comment by leomendoza123** [comment]
[[QA] Center H1 text inside email domains interstitial displayed after sign in](https://trello.com/c/T9V3QBdu/9516-qa-center-h1-text-inside-email-domains-interstitial-displayed-after-sign-in)

**Review by amontenegro — APPROVED** [review]

**Pull request merged**
