### PR TITLE
Fix/7177 7178 7170 multiple fixes

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
[When the first 10 notifications are archived, the inbox will be shown empty](https://trello.com/c/YKbTYTRX/7170-when-the-first-10-notifications-are-archived-the-inbox-will-be-shown-empty)

**Comment by leomendoza123** [comment]
[[QA] [new inbox] archiving notifications that have already been archived.](https://trello.com/c/ybcwdUBt/7177-qa-new-inbox-archiving-notifications-that-have-already-been-archived)

**Comment by leomendoza123** [comment]
[[QA] [new inbox] subject line alignment with long names](https://trello.com/c/DKjLxnON/7178-qa-new-inbox-subject-line-alignment-with-long-names)

**Comment by leomendoza123** [comment]
[[QA] [new inbox] issue clicking "archive selected" without making a selection](https://trello.com/c/dWglPdBE/7175-qa-new-inbox-issue-clicking-archive-selected-without-making-a-selection)

**Review by amontenegro — APPROVED** [review]

**Pull request merged**
