### PR TITLE
fix: Add full stop to sign in text and update claim link text

### PR DESCRIPTION
**Pull request by DanielPalafox**

### CODE REVIEW

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Comment by DanielPalafox** [comment]
[[QA] Fixes to text in sign in updates](https://trello.com/c/UAJLkMAd/9122-qa-fixes-to-text-in-sign-in-updates)

**Review by leomendoza123 — APPROVED** [review]

**Pull request merged**
