### PR TITLE
My orcid prop fixes

### PR DESCRIPTION
**Pull request by Camelia-Orcid**

### CODE REVIEW

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Fix section name in the names modal sidebar navigation](https://trello.com/c/XLWikin5/7605-qamy-orcid-fix-section-name-in-the-names-modal-sidebar-navigation)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Remove full stop from section title inside names modal](https://trello.com/c/pKLGHJNg/7610-qamy-orcid-remove-full-stop-from-section-title-inside-names-modal)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Fix field names in funding modal](https://trello.com/c/gsO3l082/7634-qamy-orcid-fix-field-names-in-funding-modal)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Fix button name in modals](https://trello.com/c/3IhyqnEA/7642-qamy-orcid-fix-button-name-in-modals)

**Review by leomendoza123 — APPROVED** [review]

**Pull request merged**
