### PR TITLE
A general review on mobile modals experience

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
[[QA][my-orcid] Element overlap in keywords modal in mobile devices](https://trello.com/c/OXAfDKzK/7562-qamy-orcid-element-overlap-in-keywords-modal-in-mobile-devices)

**Comment by leomendoza123** [comment]
[[QA][my-orcid] Element overlap in websites and social links modal in mobile devices](https://trello.com/c/ngDYw17I/7567-qamy-orcid-element-overlap-in-websites-and-social-links-modal-in-mobile-devices)

**Comment by leomendoza123** [comment]
[[QA][my-orcid] Bio that exceeds max length is discarded](https://trello.com/c/HIjmzGna/7601-qamy-orcid-bio-that-exceeds-max-length-is-discarded)

**Comment by leomendoza123** [comment]
[[QA][my-orcid] Text field inside bio modal is not resizable](https://trello.com/c/8T6IsQZQ/7602-qamy-orcid-text-field-inside-bio-modal-is-not-resizable)

**Review by DanielPalafox — APPROVED** [review]

**Pull request merged**
