### PR TITLE
add delete button in panel source

### PR DESCRIPTION
**Pull request by DanielPalafox**

### CODE REVIEW

**Comment by DanielPalafox** [comment]
[[speedup Q3] Peer reviews: delete (0.5)](https://trello.com/c/aoMyIX8h/7395-speedup-q3-peer-reviews-delete-05)

**Comment by DanielPalafox** [comment]
[[speedup Q3] Affiliations: delete (0.5)](https://trello.com/c/4okK3aIi/7397-speedup-q3-affiliations-delete-05)

**Comment by DanielPalafox** [comment]
[[speedup Q3] Funding: delete (0.5)](https://trello.com/c/ja6XMz5p/7398-speedup-q3-funding-delete-05)

**Comment by DanielPalafox** [comment]
[[speedup Q3] Works: delete (0.5)](https://trello.com/c/wt1ABS1I/7396-speedup-q3-works-delete-05)

**Review by leomendoza123 — APPROVED** [review]

**Pull request merged**
