### PR TITLE
[qa-my-orcid]  various sidebar issues

### PR DESCRIPTION
**Pull request by Camelia-Orcid**

### CODE REVIEW

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Websites and social links modal name not consistent](https://trello.com/c/HhaiONys/7566-qamy-orcid-websites-and-social-links-modal-name-not-consistent)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Fix button to add new email address in emails modal](https://trello.com/c/g8vCKwlu/7578-qamy-orcid-fix-button-to-add-new-email-address-in-emails-modal)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Keywords, max limit error message not displayed](https://trello.com/c/r59ePFsm/7560-qamy-orcid-keywords-max-limit-error-message-not-displayed)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Fix text "make primary" in emails modal](https://trello.com/c/i18XslHV/7583-qamy-orcid-fix-text-make-primary-in-emails-modal)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Other IDs modal: IDs are not clickable links](https://trello.com/c/wqKt3R8i/7570-qamy-orcid-other-ids-modal-ids-are-not-clickable-links)

**Comment by Camelia-Orcid** [comment]
[[QA][my-orcid] Typo inside emails modal "other email address" section](https://trello.com/c/pQD42Lfm/7580-qamy-orcid-typo-inside-emails-modal-other-email-address-section)

**Review by leomendoza123 — APPROVED** [review]

**Review by DanielPalafox — APPROVED** [review]

**Pull request merged**
