### PR TITLE
visiblity-issues-v3

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
[[QA] Sidebar visibility indicator dots have inconsistent aria labels](https://trello.com/c/XIvZXLlg/8621-qa-sidebar-visibility-indicator-dots-have-inconsistent-aria-labels)

**Comment by leomendoza123** [comment]
[[QA] Email modal form alignment](https://trello.com/c/qZqED5Ki/8620-qa-email-modal-form-alignment)

**Comment by leomendoza123** [comment]
[[QA] Aria-labels don't match the visibility settings inside the widget dropdown in the Emails modal](https://trello.com/c/tZ174z16/8622-qa-aria-labels-dont-match-the-visibility-settings-inside-the-widget-dropdown-in-the-emails-modal)

**Comment by leomendoza123** [comment]
[[QA] Visibility widget menu - Type and styling tweaks](https://trello.com/c/WDuoY7L5/8616-qa-visibility-widget-menu-type-and-styling-tweaks)

**Review by amontenegro — APPROVED** [review]

**Pull request merged**
