### PR TITLE
Feature/side bar public view (all items)

### PR DESCRIPTION
**Pull request by leomendoza123**

### CODE REVIEW

**Comment by leomendoza123** [comment]
[[speedup Q2] Public page: Emails (2)](https://trello.com/c/j8wJEvKx/7280-speedup-q2-public-page-emails-2)

**Comment by leomendoza123** [comment]
[[speedup Q2] Public page: Keywords (2)](https://trello.com/c/Run5cLkD/7283-speedup-q2-public-page-keywords-2)

**Comment by leomendoza123** [comment]
[[speedup Q2] Public page: Websites and social links (2)](https://trello.com/c/NRdgV78Y/7281-speedup-q2-public-page-websites-and-social-links-2)

**Comment by leomendoza123** [comment]
[[speedup Q2] Public page: Countries (2)](https://trello.com/c/ImL6jqKZ/7285-speedup-q2-public-page-countries-2)

**Comment by leomendoza123** [comment]
This PR requires this one to be merge as well https://github.com/ORCID/ORCID-Source/pull/6203

**Review by DanielPalafox — APPROVED** [review]

**Pull request merged**
