### PR TITLE
Fix/7584 qamy orcid visibility settings should not be shown when adding a new email address

### PR DESCRIPTION
**Pull request by DanielPalafox**

### CODE REVIEW

**Comment by DanielPalafox** [comment]
[[QA][my-orcid] Visibility settings should not be shown when adding a new email address](https://trello.com/c/vZiO1cWb/7584-qamy-orcid-visibility-settings-should-not-be-shown-when-adding-a-new-email-address)

**Comment by DanielPalafox** [comment]
[[QA][my-orcid] Visibility setting can be changed on unverified primary email address](https://trello.com/c/WvRBv8vR/7577-qamy-orcid-visibility-setting-can-be-changed-on-unverified-primary-email-address)

**Comment by DanielPalafox** [comment]
[[QA][my-orcid] No option to resend verification email for unverified primary email address](https://trello.com/c/VvNigPbR/7581-qamy-orcid-no-option-to-resend-verification-email-for-unverified-primary-email-address)

**Review by leomendoza123 — APPROVED** [review]

**Comment by DanielPalafox** [comment]
[[QA] [my-orcid] Issues editing unverified primary email address](https://trello.com/c/W7dV2lyo/7579-qa-my-orcid-issues-editing-unverified-primary-email-address)

**Pull request merged**
